name: map_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.0.1
  intl: ^0.18.0
  map_app_ui:
    path: ./packages/map_app_ui
  map_repository:
    path: ./packages/map_repository
  stream_transform: ^2.1.0


dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
