name: map_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  data_provider:
    path: ../data_provider
  geolocator: ^9.0.2
  latlong2: ^0.9.0
  

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.0.0

